Repository N0ise9/ITSC-4155-Software-Development, pull requests merged in 2023-03, with the labels that each got.

#54 Updates for Node.js to support window and document
  .gitignore
  src/__tests__/index.int.spec.ts
  src/__tests__/index.unit.spec.ts
  src/css/index.css
  src/index.ts
  src/js/survey.js
  src/js/window.js
  src/pages/index.html
  src/pages/survey.html
  src/pages/thankyou.html
Labels: Frontend

#52 Signup and login page
  src/images/profile-pic-placeholder.png
  src/js/hello.unit.spec.js
  src/js/index.js
  src/pages/profile.html
  src/pages/sign_in.html
  src/pages/signup-login.html
Labels: enhancement, Frontend

#53 Registration page
  src/css/registration.css
  src/pages/registration.html
Labels: enhancement, Frontend

#65 (#32) Guided prompt pages
  src/css/guided-style.css
  src/pages/dishes.html
  src/pages/flavors.html
Labels: enhancement, Frontend

#49 Create typescript node server
  package-lock.json
  package.json
  src/app.ts
  src/controllers/testController.ts
  src/js/window.js
  src/pages/dishes.html
  src/pages/flavors.html
  src/pages/index.html
  src/pages/profile.html
  src/pages/registration.html
  src/pages/sign_in.html
  src/pages/signup-login.html
  src/pages/thankyou.html
  src/public/css/guided-style.css
  src/public/css/index.css
  src/public/css/registration.css
  src/public/images/profile-pic-placeholder.png
  src/public/js/hello.unit.spec.js
  src/public/js/index.js
  src/public/js/survey.js
  src/public/js/window.js
  src/routes/routes.ts
  src/views/dishes.ejs
  src/views/flavors.ejs
  src/views/index.ejs
  src/views/partials/footer.ejs
  src/views/partials/header.ejs
  src/views/profile.ejs
  src/views/registration.ejs
  src/views/signin.ejs
  src/views/survey.ejs
  src/views/thankyou.ejs
  tsconfig.json
Labels: Frontend, Backend

#79 Css
  src/controllers/testController.ts
  src/public/css/guided-style.css
  src/public/css/index.css
  src/public/css/registration.css
  src/routes/routes.ts
  src/views/about.ejs
  src/views/dishes.ejs
  src/views/flavors.ejs
  src/views/index.ejs
  src/views/partials/footer.ejs
  src/views/partials/header.ejs
  src/views/profile.ejs
  src/views/registration.ejs
  src/views/signin.ejs
  src/views/survey.ejs
Labels: Frontend
