Repository N0ise9/ITSC-4155-Software-Development, pull requests merged in 2023-04, with the labels that each got.

#82 Yelp search
  package-lock.json
  package.json
  prisma/migrations/20230406205112_testo/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/prismaTestDelete.ts
  src/services/yelp/cleanYelp.ts
  src/services/yelp/cleanedYelp.json
  src/services/yelp/outputYelp.json
  src/services/yelp/searchYelp.ts
Labels: Backend

#80 (#48) Mapbox
  src/controllers/testController.ts
  src/public/css/results.css
  src/routes/routes.ts
  src/views/dishes.ejs
  src/views/results.ejs
Labels: enhancement, Frontend, Backend

#89 Create food
  .jest/Builder.ts
  package-lock.json
  package.json
  prisma/migrations/20230406205112_testo/migration.sql
  prisma/migrations/20230424151744_lets_eat/migration.sql
  prisma/migrations/20230427201818_418pm/migration.sql
  prisma/migrations/20230427220558_create_food/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/__tests__/algorithm.unit.spec.ts
  src/controllers/frontEndController.ts
  src/controllers/testController.ts
  src/repositories/helperRepository.ts
  src/repositories/restaurantFoodRepository.ts
  src/repositories/restaurantRepository.ts
  src/repositories/userRepository.ts
  src/services/algorithm.ts
  src/services/foodsCollection/foodImageCollection.ts
  src/services/foodsCollection/foods.json
  src/services/foodsCollection/modifiedFoods.json
  src/services/yelp/getAllYelp.ts
  src/services/yelp/searchYelp.ts
  src/utils/types.ts
  src/utils/utils.ts
  src/views/dishes.ejs
  src/views/results.ejs
  tsconfig.json
Labels: Backend

#91 Algorithm testing-Sarnam
  package-lock.json
  package.json
  src/__tests__/cuisineMatches.unit.spec.ts
  src/__tests__/types.unit.spec.ts
Labels: bug, Backend
